// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type SensorDatum struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Long      float64
	Lat       float64
}

type WindDatum struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	SensorID  uuid.UUID
	WindID    uuid.UUID
}

type WindSpeed struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Windangle    int32
	Windstrength int32
	Gustangle    int32
	Guststrength int32
}
