// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wind_speed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWindSpeed = `-- name: CreateWindSpeed :one
INSERT INTO wind_speed(id, created_at, updated_at, WindAngle, WindStrength, GustAngle, GustStrength)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, windangle, windstrength, gustangle, guststrength
`

type CreateWindSpeedParams struct {
	ID           uuid.UUID
	Windangle    int32
	Windstrength int32
	Gustangle    int32
	Guststrength int32
}

func (q *Queries) CreateWindSpeed(ctx context.Context, arg CreateWindSpeedParams) (WindSpeed, error) {
	row := q.db.QueryRowContext(ctx, createWindSpeed,
		arg.ID,
		arg.Windangle,
		arg.Windstrength,
		arg.Gustangle,
		arg.Guststrength,
	)
	var i WindSpeed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Windangle,
		&i.Windstrength,
		&i.Gustangle,
		&i.Guststrength,
	)
	return i, err
}
